#!/bin/bash

files=`cat <<EOT
Xmodmap
Xresources
emacs.d
ghci
gitconfig
mlterm
screenrc
skk
tmux.conf
vim
vimperator
vimperatorrc
vimrc
xmobarrc
xmonad
xsession
zlogin
zlogout
zprofile
zsh
zshenv
zshrc
EOT`

for f in $files ; do
    rm -f ~/.$f
    ln -f -s $PWD/$f ~/.$f
done
