#!/bin/sh

set -x
{
cat <<EOT
Xmodmap             .Xmodmap
Xdefaults           .Xdefaults
emacs.d             .emacs.d
ghci                .ghci
gitconfig           .gitconfig
imwheelrc           .imwheelrc
latexmkrc           .latexmkrc
skk                 .skk
sway                .sway
tmux.conf           .tmux.conf
vim                 .vim
vimrc               .vimrc
xkb                 .xkb
xmobarrc            .xmobarrc
xmonad              .xmonad
xsessionrc          .xsessionrc
zsh.d               .zsh.d
zshenv              .zshenv
EOT
} | while read origin symlink ; do
    rm -f ~/$symlink
    ln -f -s $PWD/$origin ~/$symlink
done
