#!/bin/sh

set -x
{
cat <<EOT
Xmodmap             .Xmodmap
Xresources          .Xresources
emacs.d             .emacs.d
ghci                .ghci
gitconfig           .gitconfig
latexmkrc           .latexmkrc
skk                 .skk
tmux.conf           .tmux.conf
vim                 .vim
vimrc               .vimrc
xmobarrc            .xmobarrc
xmonad              .xmonad
xsession            .xsession
zsh.d               .zsh.d
zshenv              .zshenv
EOT
} | while read origin symlink ; do
    rm -f ~/$symlink
    ln -f -s $PWD/$origin ~/$symlink
done
